//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCOT.UI.WinForm.B2CTicketWebServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://asms.vetech.cn/B2CMemberWebService", ConfigurationName="B2CTicketWebServices.B2CMemberWebServicePortType")]
    public interface B2CMemberWebServicePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string singleFrequentFlyerSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelTicketOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string hotelOrdersDetailSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string searchTourismOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string checkMember(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelApprOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelTravelOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getPassWordBySj(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketOrdersDetailSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string syncMember(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelTourismOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string findSpecialOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string deleteFrequentFlyer(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string hotelOrdersDetailSearchBy(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string singlePointExchangeSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketRequirementDetailSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string querySpecialOrders(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string pointsExchangeRecordsSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string login(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string singlePointDetailSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketDynamic(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string repeatUsername(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancleSpecialOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string travelOrdersSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketOrdersSearchByType(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getAdviseList(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string modifySpecialOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string syncEciticLogin(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string registration(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string memberAdvise(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string getMembers(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string pointsDetailsSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string cancelHotelOrder(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string checkOrderStatus(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string travelOrdersDetailSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketOrdersSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string queryTraveler(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string frequentFlyerSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string infoPassModify(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string forgetPass(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string hotelOrdersSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string ticketRequirementSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string pointsSearch(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string frequentFlyerAddOrModify(string in0, string in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        string checkFrequentFlyer(string in0, string in1, string in2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B2CMemberWebServicePortTypeChannel : YCOT.UI.WinForm.B2CTicketWebServices.B2CMemberWebServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2CMemberWebServicePortTypeClient : System.ServiceModel.ClientBase<YCOT.UI.WinForm.B2CTicketWebServices.B2CMemberWebServicePortType>, YCOT.UI.WinForm.B2CTicketWebServices.B2CMemberWebServicePortType {
        
        public B2CMemberWebServicePortTypeClient() {
        }
        
        public B2CMemberWebServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2CMemberWebServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2CMemberWebServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2CMemberWebServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string singleFrequentFlyerSearch(string in0, string in1, string in2) {
            return base.Channel.singleFrequentFlyerSearch(in0, in1, in2);
        }
        
        public string cancelTicketOrder(string in0, string in1, string in2) {
            return base.Channel.cancelTicketOrder(in0, in1, in2);
        }
        
        public string hotelOrdersDetailSearch(string in0, string in1, string in2) {
            return base.Channel.hotelOrdersDetailSearch(in0, in1, in2);
        }
        
        public string searchTourismOrder(string in0, string in1, string in2) {
            return base.Channel.searchTourismOrder(in0, in1, in2);
        }
        
        public string checkMember(string in0, string in1, string in2) {
            return base.Channel.checkMember(in0, in1, in2);
        }
        
        public string cancelApprOrder(string in0, string in1, string in2) {
            return base.Channel.cancelApprOrder(in0, in1, in2);
        }
        
        public string cancelTravelOrder(string in0, string in1, string in2) {
            return base.Channel.cancelTravelOrder(in0, in1, in2);
        }
        
        public string getPassWordBySj(string in0, string in1, string in2) {
            return base.Channel.getPassWordBySj(in0, in1, in2);
        }
        
        public string ticketOrdersDetailSearch(string in0, string in1, string in2) {
            return base.Channel.ticketOrdersDetailSearch(in0, in1, in2);
        }
        
        public string syncMember(string in0, string in1, string in2) {
            return base.Channel.syncMember(in0, in1, in2);
        }
        
        public string cancelTourismOrder(string in0, string in1, string in2) {
            return base.Channel.cancelTourismOrder(in0, in1, in2);
        }
        
        public string findSpecialOrder(string in0, string in1, string in2) {
            return base.Channel.findSpecialOrder(in0, in1, in2);
        }
        
        public string deleteFrequentFlyer(string in0, string in1, string in2) {
            return base.Channel.deleteFrequentFlyer(in0, in1, in2);
        }
        
        public string hotelOrdersDetailSearchBy(string in0, string in1, string in2) {
            return base.Channel.hotelOrdersDetailSearchBy(in0, in1, in2);
        }
        
        public string singlePointExchangeSearch(string in0, string in1, string in2) {
            return base.Channel.singlePointExchangeSearch(in0, in1, in2);
        }
        
        public string ticketRequirementDetailSearch(string in0, string in1, string in2) {
            return base.Channel.ticketRequirementDetailSearch(in0, in1, in2);
        }
        
        public string querySpecialOrders(string in0, string in1, string in2) {
            return base.Channel.querySpecialOrders(in0, in1, in2);
        }
        
        public string pointsExchangeRecordsSearch(string in0, string in1, string in2) {
            return base.Channel.pointsExchangeRecordsSearch(in0, in1, in2);
        }
        
        public string login(string in0, string in1, string in2) {
            return base.Channel.login(in0, in1, in2);
        }
        
        public string singlePointDetailSearch(string in0, string in1, string in2) {
            return base.Channel.singlePointDetailSearch(in0, in1, in2);
        }
        
        public string ticketDynamic(string in0, string in1, string in2) {
            return base.Channel.ticketDynamic(in0, in1, in2);
        }
        
        public string repeatUsername(string in0, string in1, string in2) {
            return base.Channel.repeatUsername(in0, in1, in2);
        }
        
        public string cancleSpecialOrder(string in0, string in1, string in2) {
            return base.Channel.cancleSpecialOrder(in0, in1, in2);
        }
        
        public string travelOrdersSearch(string in0, string in1, string in2) {
            return base.Channel.travelOrdersSearch(in0, in1, in2);
        }
        
        public string ticketOrdersSearchByType(string in0, string in1, string in2) {
            return base.Channel.ticketOrdersSearchByType(in0, in1, in2);
        }
        
        public string getAdviseList(string in0, string in1, string in2) {
            return base.Channel.getAdviseList(in0, in1, in2);
        }
        
        public string modifySpecialOrder(string in0, string in1, string in2) {
            return base.Channel.modifySpecialOrder(in0, in1, in2);
        }
        
        public string syncEciticLogin(string in0, string in1, string in2) {
            return base.Channel.syncEciticLogin(in0, in1, in2);
        }
        
        public string registration(string in0, string in1, string in2) {
            return base.Channel.registration(in0, in1, in2);
        }
        
        public string memberAdvise(string in0, string in1, string in2) {
            return base.Channel.memberAdvise(in0, in1, in2);
        }
        
        public string getMembers(string in0, string in1, string in2) {
            return base.Channel.getMembers(in0, in1, in2);
        }
        
        public string pointsDetailsSearch(string in0, string in1, string in2) {
            return base.Channel.pointsDetailsSearch(in0, in1, in2);
        }
        
        public string cancelHotelOrder(string in0, string in1, string in2) {
            return base.Channel.cancelHotelOrder(in0, in1, in2);
        }
        
        public string checkOrderStatus(string in0, string in1, string in2) {
            return base.Channel.checkOrderStatus(in0, in1, in2);
        }
        
        public string travelOrdersDetailSearch(string in0, string in1, string in2) {
            return base.Channel.travelOrdersDetailSearch(in0, in1, in2);
        }
        
        public string ticketOrdersSearch(string in0, string in1, string in2) {
            return base.Channel.ticketOrdersSearch(in0, in1, in2);
        }
        
        public string queryTraveler(string in0, string in1, string in2) {
            return base.Channel.queryTraveler(in0, in1, in2);
        }
        
        public string frequentFlyerSearch(string in0, string in1, string in2) {
            return base.Channel.frequentFlyerSearch(in0, in1, in2);
        }
        
        public string infoPassModify(string in0, string in1, string in2) {
            return base.Channel.infoPassModify(in0, in1, in2);
        }
        
        public string forgetPass(string in0, string in1, string in2) {
            return base.Channel.forgetPass(in0, in1, in2);
        }
        
        public string hotelOrdersSearch(string in0, string in1, string in2) {
            return base.Channel.hotelOrdersSearch(in0, in1, in2);
        }
        
        public string ticketRequirementSearch(string in0, string in1, string in2) {
            return base.Channel.ticketRequirementSearch(in0, in1, in2);
        }
        
        public string pointsSearch(string in0, string in1, string in2) {
            return base.Channel.pointsSearch(in0, in1, in2);
        }
        
        public string frequentFlyerAddOrModify(string in0, string in1, string in2) {
            return base.Channel.frequentFlyerAddOrModify(in0, in1, in2);
        }
        
        public string checkFrequentFlyer(string in0, string in1, string in2) {
            return base.Channel.checkFrequentFlyer(in0, in1, in2);
        }
    }
}
