//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCOT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admins
    {
        public Admins()
        {
            this.Auth_AdminRole = new HashSet<Auth_AdminRole>();
        }
    
        public int id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Auth_AdminControllerAction Auth_AdminControllerAction { get; set; }
        public virtual ICollection<Auth_AdminRole> Auth_AdminRole { get; set; }
    }
}
