//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCOT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_Roles
    {
        public Auth_Roles()
        {
            this.Auth_AdminRole = new HashSet<Auth_AdminRole>();
            this.Auth_ControllerActionRole = new HashSet<Auth_ControllerActionRole>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Auth_AdminRole> Auth_AdminRole { get; set; }
        public virtual ICollection<Auth_ControllerActionRole> Auth_ControllerActionRole { get; set; }
    }
}
