//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCOT.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auth_AdminControllerAction
    {
        public int ID { get; set; }
        public int AdminID { get; set; }
        public int ControllerActionID { get; set; }
        public Nullable<bool> IsRefuse { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Auth_ControllerActions Auth_ControllerActions { get; set; }
    }
}
