//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YCOT.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YCOT_DataEntities : DbContext
    {
        public YCOT_DataEntities()
            : base("name=YCOT_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admins> Admins { get; set; }
        public DbSet<Auth_AdminControllerAction> Auth_AdminControllerAction { get; set; }
        public DbSet<Auth_AdminRole> Auth_AdminRole { get; set; }
        public DbSet<Auth_ControllerActionRole> Auth_ControllerActionRole { get; set; }
        public DbSet<Auth_ControllerActions> Auth_ControllerActions { get; set; }
        public DbSet<Auth_Roles> Auth_Roles { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
